// peclet-morton C ABI: the exported functions of libpeclet_morton_c.
//
// Every function operates on whole arrays (codes always as uint64_t, coordinates as the fixed-width
// unsigned type of the configuration) so a caller with no per-element overhead of its own -- the
// ctypes-based Python package, or any other language -- gets the library's dispatched batch paths.
//
// Four configurations are instantiated, named <dims>_<coord suffix>:
//   2D, 32 bits/axis  -> *2_u32   (uint32_t coords)
//   2D, 16 bits/axis  -> *2_u16   (uint16_t coords)
//   3D, 21 bits/axis  -> *3_u32   (uint32_t coords)
//   3D, 16 bits/axis  -> *3_u16   (uint16_t coords)
//
// The declarations are generated by the PECLET_MORTON_C_DECLARE_2D/3D macros below, and
// bindings/morton_c.cpp includes this header before defining the functions with the mirrored
// DEFINE_2D/3D macros, so a signature that drifts between the two is a compile error, not a
// silent ABI change. Adding a configuration means one PECLET_MORTON_C_DECLARE_* line here, one
// DEFINE_* line in the .cpp, and an entry in `_CONFIG` in the Python package.
//
// SPDX-License-Identifier: MIT
#ifndef PECLET_MORTON_C_H
#define PECLET_MORTON_C_H

#include <stddef.h>
#include <stdint.h>

#if defined(_WIN32)
#if defined(PECLET_MORTON_C_BUILD)
#define PECLET_MORTON_C_API __declspec(dllexport)
#else
#define PECLET_MORTON_C_API __declspec(dllimport)
#endif
#else
#define PECLET_MORTON_C_API __attribute__((visibility("default")))
#endif

#ifdef __cplusplus
extern "C" {
#endif

// clang-format off
// Per-configuration function set. Arguments:
//   x, y, z    : coordinate arrays of length n (COORD = uint32_t or uint16_t)
//   code / out : Morton codes as uint64_t (arrays of length n unless stated otherwise)
//   axis       : 0..dims-1;  k : signed per-axis displacement
//   lo, hi     : inclusive integer box corners, arrays of length dims
//
//   encode<D>       interleave the coordinate arrays into codes
//   decode<D>       inverse of encode
//   add<D>          out = code moved by k along axis, in Morton space (wraps modulo 2^bits)
//   addsat<D>       as add, but saturating at [0, 2^bits - 1]
//   tryadd<D>       bounds-checked add: ok[i] = 1 and out[i] moved, or ok[i] = 0 and out[i] = code[i]
//   faceneighbors<D> out is n x (2*D): the von Neumann neighbours, columns [-x,+x,-y,+y(,-z,+z)]
//   allneighbors<D> out is n x (3^D - 1): the Moore neighbours
//   box_count<D>    number of cells in the inclusive box [lo, hi] (0 if hi < lo on any axis)
//   box_zorder<D>   all codes in the inclusive box [lo, hi] in increasing code order; out must
//                   hold box_count<D>(lo, hi) entries
#define PECLET_MORTON_C_DECLARE_2D(SUFFIX, COORD)                                                                            \
  PECLET_MORTON_C_API void     peclet_morton_encode2_##SUFFIX(const COORD* x, const COORD* y, uint64_t* out, size_t n);      \
  PECLET_MORTON_C_API void     peclet_morton_decode2_##SUFFIX(const uint64_t* code, COORD* x, COORD* y, size_t n);           \
  PECLET_MORTON_C_API void     peclet_morton_add2_##SUFFIX(const uint64_t* code, uint64_t* out, size_t n, unsigned axis,     \
                                                           int64_t k);                                                       \
  PECLET_MORTON_C_API void     peclet_morton_addsat2_##SUFFIX(const uint64_t* code, uint64_t* out, size_t n, unsigned axis,  \
                                                              int64_t k);                                                    \
  PECLET_MORTON_C_API void     peclet_morton_tryadd2_##SUFFIX(const uint64_t* code, uint64_t* out, uint8_t* ok, size_t n,    \
                                                              unsigned axis, int64_t k);                                     \
  PECLET_MORTON_C_API void     peclet_morton_faceneighbors2_##SUFFIX(const uint64_t* code, uint64_t* out, size_t n);         \
  PECLET_MORTON_C_API void     peclet_morton_allneighbors2_##SUFFIX(const uint64_t* code, uint64_t* out, size_t n);          \
  PECLET_MORTON_C_API uint64_t peclet_morton_box_count2_##SUFFIX(const COORD* lo, const COORD* hi);                          \
  PECLET_MORTON_C_API void     peclet_morton_box_zorder2_##SUFFIX(const COORD* lo, const COORD* hi, uint64_t* out);

#define PECLET_MORTON_C_DECLARE_3D(SUFFIX, COORD)                                                                            \
  PECLET_MORTON_C_API void     peclet_morton_encode3_##SUFFIX(const COORD* x, const COORD* y, const COORD* z, uint64_t* out, \
                                                              size_t n);                                                     \
  PECLET_MORTON_C_API void     peclet_morton_decode3_##SUFFIX(const uint64_t* code, COORD* x, COORD* y, COORD* z, size_t n); \
  PECLET_MORTON_C_API void     peclet_morton_add3_##SUFFIX(const uint64_t* code, uint64_t* out, size_t n, unsigned axis,     \
                                                           int64_t k);                                                       \
  PECLET_MORTON_C_API void     peclet_morton_addsat3_##SUFFIX(const uint64_t* code, uint64_t* out, size_t n, unsigned axis,  \
                                                              int64_t k);                                                    \
  PECLET_MORTON_C_API void     peclet_morton_tryadd3_##SUFFIX(const uint64_t* code, uint64_t* out, uint8_t* ok, size_t n,    \
                                                              unsigned axis, int64_t k);                                     \
  PECLET_MORTON_C_API void     peclet_morton_faceneighbors3_##SUFFIX(const uint64_t* code, uint64_t* out, size_t n);         \
  PECLET_MORTON_C_API void     peclet_morton_allneighbors3_##SUFFIX(const uint64_t* code, uint64_t* out, size_t n);          \
  PECLET_MORTON_C_API uint64_t peclet_morton_box_count3_##SUFFIX(const COORD* lo, const COORD* hi);                          \
  PECLET_MORTON_C_API void     peclet_morton_box_zorder3_##SUFFIX(const COORD* lo, const COORD* hi, uint64_t* out);
// clang-format on

PECLET_MORTON_C_DECLARE_2D(u32, uint32_t)  // Morton<2, 32>
PECLET_MORTON_C_DECLARE_2D(u16, uint16_t)  // Morton<2, 16>
PECLET_MORTON_C_DECLARE_3D(u32, uint32_t)  // Morton<3, 21>
PECLET_MORTON_C_DECLARE_3D(u16, uint16_t)  // Morton<3, 16>

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // PECLET_MORTON_C_H
